-- DO NOT EDIT THIS FILE MANUALLY
--File placeholder for version information, will be replaced on release build.

local VERSION_INFO=
{
    version = "0.0.0",
    commit = "0000000000000000000000000000000000000000",
}

return VERSION_INFO
